
## 📈 Momentum Screener - HTML Report Generator (Test Mode)
This notebook lets you generate HTML reports for past Fridays and update the GitHub Pages `index.html` to preview how the report site will look.

In [1]:
 # Setup paths and imports

import sys, os
from datetime import datetime
import pandas as pd
from dotenv import load_dotenv
# Define key directories

NOTEBOOK_DIR = os.getcwd()

BASE_DIR = os.path.abspath(os.path.join(NOTEBOOK_DIR, ".."))
SRC_DIR = os.path.join(BASE_DIR, "src")


REPORT_DIR = os.path.join(BASE_DIR, "reports")

sys.path.insert(0, SRC_DIR)
os.makedirs(REPORT_DIR, exist_ok=True)
load_dotenv()

True

In [2]:
# Import screener modules
from prices import get_target_dates, download_all_required_price_data
from ranking import get_price_snapshots, compute_returns_and_ranks, store_top10_picks
from report import cache_company_data
from emailer import format_html_email

In [9]:
# patch database to take last week return
import sqlite3
BASE_DIR = os.path.abspath(os.path.join(NOTEBOOK_DIR, ".."))

db_path = os.path.join(BASE_DIR, "data", "market_data.sqlite")

conn = sqlite3.connect(db_path)
cur  = conn.cursor()

# --- safety check: only add it if it isn't there already ---
cur.execute("PRAGMA table_info(top10_picks);")
cols = [row[1] for row in cur.fetchall()]    # row[1] = column name
if "last_week_return" not in cols:
    cur.execute("ALTER TABLE top10_picks ADD COLUMN last_week_return TEXT;")
    conn.commit()

conn.close()

In [3]:

# Function to generate a single HTML report\n",
def generate_html_for_date(friday_str):
    print(f"⏳ Generating report for {friday_str}")

    anchor = pd.Timestamp(friday_str)      
    download_all_required_price_data(today = anchor)
    target_dates = get_target_dates(today=anchor)
    df, resolved = get_price_snapshots(target_dates)
    ranks = compute_returns_and_ranks(df, resolved)
    print(ranks)
    print(ranks.dtypes)
    top10 = store_top10_picks(ranks, run_date=anchor)
    
    if top10.empty:
        print("⚠️ No top 10 results to include.")
        return

    tickers = top10["ticker"].tolist()
    cache_company_data(tickers)
    html_content = format_html_email(top10, report_date=anchor)
    
    output_path = os.path.join(REPORT_DIR, f"momentum_{friday_str}.html")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html_content)
    
    print(f"✅ Report written: {output_path}")

In [17]:
anchor = pd.Timestamp("2025-06-13")
target_dates = get_target_dates(today=anchor)
target_dates
df, resolved = get_price_snapshots(target_dates)
ranks = compute_returns_and_ranks(df, resolved)
ranks
#print(ranks.dtypes)
top10 = store_top10_picks(ranks, run_date=anchor)
top10

       current_return last_week_return last_month_return  current_rank  \
ticker
PLTR           468.7%            12.7%            475.0%           1.0
GEV            174.7%             0.7%            149.1%           2.0
AXON           162.0%            -1.7%            128.4%           3.0
HWM            105.6%            -2.0%             94.1%           4.0
VST             92.0%             1.8%             56.4%           5.0

        last_month_rank  rank_change
ticker
PLTR                1.0          0.0
GEV                 2.0          0.0
AXON                3.0          0.0
HWM                 6.0          2.0
VST                27.0         22.0
✅ Stored top 10 picks for 2025-06-13

,ticker,current_return,last_week_return,last_month_return,current_rank,last_month_rank,rank_change,date
0,PLTR,468.7%,12.7%,475.0%,1.0,1.0,0.0,2025-06-13
1,GEV,174.7%,0.7%,149.1%,2.0,2.0,0.0,2025-06-13
2,AXON,162.0%,-1.7%,128.4%,3.0,3.0,0.0,2025-06-13
3,HWM,105.6%,-2.0%,94.1%,4.0,6.0,2.0,2025-06-13
4,VST,92.0%,1.8%,56.4%,5.0,27.0,22.0,2025-06-13
5,DASH,88.3%,0.4%,67.3%,7.0,13.0,6.0,2025-06-13
6,NRG,88.0%,-3.2%,80.0%,8.0,10.0,2.0,2025-06-13
7,NFLX,86.9%,-2.8%,81.7%,9.0,9.0,0.0,2025-06-13
8,PM,79.3%,1.2%,65.4%,11.0,15.0,4.0,2025-06-13
9,GILD,74.2%,1.4%,57.4%,12.0,24.0,12.0,2025-06-13

Thinking through Traceback:
- generate_html_for_date

In [10]:
import sys, importlib
importlib.reload(sys.modules["emailer"])

In [ ]:
generate_html_for_date("2025-06-13")
generate_html_for_date("2025-06-20")
generate_html_for_date("2025-06-27")
generate_html_for_date("2025-07-04")

⏳ Generating report for 2025-06-13
Skipping 2025-06-12 — already in DB
Skipping SPX for 2025-06-12 — already in DB
Skipping 2025-06-05 — already in DB
Skipping SPX for 2025-06-05 — already in DB
Skipping 2024-06-12 — already in DB
Skipping SPX for 2024-06-12 — already in DB
Skipping 2025-05-12 — already in DB
Skipping SPX for 2025-05-12 — already in DB
Fetching grouped prices for 2024-05-12...
No data for 2024-05-12 — trying previous weekday...
Skipping 2024-05-10 — already in DB
Fetching SPX price for 2024-05-12...
No SPX data for 2024-05-12 — trying previous weekday...
Skipping SPX for 2024-05-10 — already in DB
       current_return last_week_return last_month_return  current_rank  \
ticker
PLTR           468.7%            12.7%            475.0%           1.0
GEV            174.7%             0.7%            149.1%           2.0
AXON           162.0%            -1.7%            128.4%           3.0
HWM            105.6%            -2.0%             94.1%           4.0
VST             92.0%             1.8%             56.4%           5.0
...               ...              ...               ...           ...
BIIB           -42.6%             1.5%            -43.8%         493.0
SMCI           -44.0%             6.4%            -58.0%         494.0
ALB            -44.5%             6.5%            -52.5%         496.0
ENPH           -66.8%             8.2%            -55.8%         499.0
MRNA           -81.5%             4.7%            -78.1%         500.0

        last_month_rank  rank_change
ticker
PLTR                1.0          0.0
GEV                 2.0          0.0
AXON                3.0          0.0
HWM                 6.0          2.0
VST                27.0         22.0
...                 ...          ...
BIIB              495.0          2.0
SMCI              500.0          6.0
ALB               498.0          2.0
ENPH              499.0          0.0
MRNA              501.0          1.0

[279 rows x 6 columns]
current_return        object
last_week_return      object
last_month_return     object
current_rank         float64
last_month_rank      float64
rank_change          float64
dtype: object
       current_return last_week_return last_month_return  current_rank  \
ticker
PLTR           468.7%            12.7%            475.0%           1.0
GEV            174.7%             0.7%            149.1%           2.0
AXON           162.0%            -1.7%            128.4%           3.0
HWM            105.6%            -2.0%             94.1%           4.0
VST             92.0%             1.8%             56.4%           5.0

        last_month_rank  rank_change
ticker
PLTR                1.0          0.0
GEV                 2.0          0.0
AXON                3.0          0.0
HWM                 6.0          2.0
VST                27.0         22.0
✅ Stored top 10 picks for 2025-06-13
🔍 Processing PLTR (1/10)
  📦 Recent news articles: 5
  ✅ News already fresh — skipping API call.
🔍 Processing GEV (2/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing AXON (3/10)
  📦 Recent news articles: 1
  ✅ News already fresh — skipping API call.
🔍 Processing HWM (4/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing VST (5/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing DASH (6/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing NRG (7/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing NFLX (8/10)
  📦 Recent news articles: 3
  ✅ News already fresh — skipping API call.
🔍 Processing PM (9/10)
  📦 Recent news articles: 1
  ✅ News already fresh — skipping API call.
🔍 Processing GILD (10/10)
  📦 Recent news articles: 1
  ✅ News already fresh — skipping API call.
  ticker current_return last_week_return
0   PLTR         468.7%            12.7%
1    GEV         174.7%             0.7%
2   AXON         162.0%            -1.7%
3    HWM         105.6%            -2.0%
4    VST          92.0%             1.8%
[0.127, 0.006999999999999999, -0.017, -0.02, 0.018000000000000002]
📅 Resolved VOO dates: {'current': '2025-06-12', 'one_year_ago': '2024-06-13', 'one_week_ago': '2025-06-05'}
📈 Retrieved VOO prices: {'2024-06-13': 498.58, '2025-06-05': 545.09, '2025-06-12': 554.95}
🔎 All compare tickers: ['GILD', 'PLTR', 'GEV', 'NRG', 'PM', 'VST', 'PAYC', 'DASH', 'NFLX', 'AVGO', 'FFIV', 'HWM', 'AXON']
🔎 Available price tickers: ['AVGO', 'AXON', 'DASH', 'FFIV', 'GEV', 'GILD', 'HWM', 'NFLX', 'NRG', 'PAYC', 'PLTR', 'PM', 'VST']
🔎 Tickers in report: ['PLTR', 'GEV', 'AXON', 'HWM', 'VST', 'DASH', 'NRG', 'NFLX', 'PM', 'GILD']
🔎 Prices dict keys: ['AVGO', 'AXON', 'DASH', 'FFIV', 'GEV', 'GILD', 'HWM', 'NFLX', 'NRG', 'PAYC']
✅ Summary HTML block:
 <p><strong>Benchmark (VOO):</strong> $554.95 (<span style="color:#006400;">+11.3%</span> last 12M, <span style="color:#006400;">+1.8%</span> last week)</p><h3>Summary of Changes</h3><p>PLTR – $135.19 (<span style="color:#006400;">+468.7%</span> last 12M, <span style="color:#006400;">+12.7%</span> last week)<br>GEV – $487.67 (<span style="color:#006400;">+174.7%</span> last 12M, <span style="color:#006400;">+0.7%</span> last week)<br>AXON – $775.20 (<span style="color:#006400;">+162.0%</span> las
🧪 DEBUG: Jinja context types and sample values:
  summary_html: <class 'str'> <p><strong>Benchmark (VOO):</strong> $554.95 (<span style="color:#006400;">+11.3%</span> last 12M, <span style="color:#006400;">+1.8%</span> last week)</p><h3>Summary of Changes</h3><p>PLTR – $135.19
  formatted_date: <class 'str'> June 13, 2025
  voo_now: <class 'numpy.float64'> 554.95
  enriched (length): 10
    First stock:
      ticker: <class 'str'> PLTR
      price: <class 'str'> 135.19
      current_return: <class 'str'> 468.7%
      last_month_return: <class 'str'> 475.0%
      rank_change: <class 'float'> 0.0
✅ Report written: /Users/zacseidel/Documents/GitHub/momentum-screener/reports/momentum_2025-06-13.html
⏳ Generating report for 2025-06-20
Fetching grouped prices for 2025-06-19...
No data for 2025-06-19 — trying previous weekday...
Skipping 2025-06-18 — already in DB
Fetching SPX price for 2025-06-19...
No SPX data for 2025-06-19 — trying previous weekday...
Skipping SPX for 2025-06-18 — already in DB
Skipping 2025-06-12 — already in DB
Skipping SPX for 2025-06-12 — already in DB
Fetching grouped prices for 2024-06-19...
No data for 2024-06-19 — trying previous weekday...
Skipping 2024-06-18 — already in DB
Fetching SPX price for 2024-06-19...
No SPX data for 2024-06-19 — trying previous weekday...
Skipping SPX for 2024-06-18 — already in DB
Skipping 2025-05-19 — already in DB
Skipping SPX for 2025-05-19 — already in DB
Fetching grouped prices for 2024-05-19...
No data for 2024-05-19 — trying previous weekday...
Skipping 2024-05-17 — already in DB
Fetching SPX price for 2024-05-19...
No SPX data for 2024-05-19 — trying previous weekday...
Skipping SPX for 2024-05-17 — already in DB
       current_return last_week_return last_month_return  current_rank  \
ticker
PLTR           442.1%             3.5%            480.6%           1.0
GEV            173.0%             0.5%            174.6%           2.0
AXON           162.6%            -0.6%            157.0%           3.0
HWM            112.3%            -0.8%            100.5%           4.0
VST            106.8%             4.2%             67.2%           5.0
...               ...              ...               ...           ...
ALB            -40.3%            -4.9%            -54.8%         489.0
AES            -44.5%            -8.8%            -45.0%         493.0
ENPH           -69.4%           -18.6%            -57.3%         498.0
MRNA           -80.9%            -7.1%            -80.1%         499.0
ORLY           -91.6%            -3.0%            -90.8%         500.0

        last_month_rank  rank_change
ticker
PLTR                1.0          0.0
GEV                 2.0          0.0
AXON                3.0          0.0
HWM                 5.0          1.0
VST                17.0         12.0
...                 ...          ...
ALB               497.0          8.0
AES               493.0          0.0
ENPH              498.0          0.0
MRNA              499.0          0.0
ORLY              500.0          0.0

[264 rows x 6 columns]
current_return        object
last_week_return      object
last_month_return     object
current_rank         float64
last_month_rank      float64
rank_change          float64
dtype: object
       current_return last_week_return last_month_return  current_rank  \
ticker
PLTR           442.1%             3.5%            480.6%           1.0
GEV            173.0%             0.5%            174.6%           2.0
AXON           162.6%            -0.6%            157.0%           3.0
HWM            112.3%            -0.8%            100.5%           4.0
VST            106.8%             4.2%             67.2%           5.0

        last_month_rank  rank_change
ticker
PLTR                1.0          0.0
GEV                 2.0          0.0
AXON                3.0          0.0
HWM                 5.0          1.0
VST                17.0         12.0
✅ Stored top 10 picks for 2025-06-20
🔍 Processing PLTR (1/10)
  📦 Recent news articles: 5
  ✅ News already fresh — skipping API call.
🔍 Processing GEV (2/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing AXON (3/10)
  📦 Recent news articles: 1
  ✅ News already fresh — skipping API call.
🔍 Processing HWM (4/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing VST (5/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing TPR (6/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing DASH (7/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing PM (8/10)
  📦 Recent news articles: 1
  ✅ News already fresh — skipping API call.
🔍 Processing GILD (9/10)
  📦 Recent news articles: 1
  ✅ News already fresh — skipping API call.
🔍 Processing FTNT (10/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
  ticker current_return last_week_return
0   PLTR         442.1%             3.5%
1    GEV         173.0%             0.5%
2   AXON         162.6%            -0.6%
3    HWM         112.3%            -0.8%
4    VST         106.8%             4.2%
[0.035, 0.005, -0.006, -0.008, 0.042]
📅 Resolved VOO dates: {'current': '2025-06-18', 'one_year_ago': '2024-06-18', 'one_week_ago': '2025-06-12'}
📈 Retrieved VOO prices: {'2024-06-18': 504.28, '2025-06-12': 554.95, '2025-06-18': 549.24}
🔎 All compare tickers: ['GILD', 'PLTR', 'GEV', 'NRG', 'PM', 'TPR', 'VST', 'DASH', 'NFLX', 'FTNT', 'HWM', 'AXON']
🔎 Available price tickers: []
🔎 Tickers in report: ['PLTR', 'GEV', 'AXON', 'HWM', 'VST', 'TPR', 'DASH', 'PM', 'GILD', 'FTNT']
🔎 Prices dict keys: []
✅ Summary HTML block:
 <p><strong>Benchmark (VOO):</strong> $549.24 (<span style="color:#006400;">+8.9%</span> last 12M, <span style="color:#c42020;">−1.0%</span> last week)</p><h3>Summary of Changes</h3><p>PLTR – $— (<span style="color:#006400;">+442.1%</span> last 12M, <span style="color:#006400;">+3.5%</span> last week)<br>GEV – $— (<span style="color:#006400;">+173.0%</span> last 12M, <span style="color:#006400;">+0.5%</span> last week)<br>AXON – $— (<span style="color:#006400;">+162.6%</span> last 12M, <span styl
🧪 DEBUG: Jinja context types and sample values:
  summary_html: <class 'str'> <p><strong>Benchmark (VOO):</strong> $549.24 (<span style="color:#006400;">+8.9%</span> last 12M, <span style="color:#c42020;">−1.0%</span> last week)</p><h3>Summary of Changes</h3><p>PLTR – $— (<span
  formatted_date: <class 'str'> June 20, 2025
  voo_now: <class 'numpy.float64'> 549.24
  enriched (length): 10
    First stock:
      ticker: <class 'str'> PLTR
      price: <class 'str'> —
      current_return: <class 'str'> 442.1%
      last_month_return: <class 'str'> 480.6%
      rank_change: <class 'float'> 0.0
✅ Report written: /Users/zacseidel/Documents/GitHub/momentum-screener/reports/momentum_2025-06-20.html
⏳ Generating report for 2025-06-27
Skipping 2025-06-26 — already in DB
Skipping SPX for 2025-06-26 — already in DB
Fetching grouped prices for 2025-06-19...
No data for 2025-06-19 — trying previous weekday...
Skipping 2025-06-18 — already in DB
Fetching SPX price for 2025-06-19...
No SPX data for 2025-06-19 — trying previous weekday...
Skipping SPX for 2025-06-18 — already in DB
Skipping 2024-06-26 — already in DB
Skipping SPX for 2024-06-26 — already in DB
Fetching grouped prices for 2025-05-26...
No data for 2025-05-26 — trying previous weekday...
Skipping 2025-05-23 — already in DB
Fetching SPX price for 2025-05-26...
No SPX data for 2025-05-26 — trying previous weekday...
Skipping SPX for 2025-05-23 — already in DB
Fetching grouped prices for 2024-05-26...
No data for 2024-05-26 — trying previous weekday...
Skipping 2024-05-24 — already in DB
Fetching SPX price for 2024-05-26...
No SPX data for 2024-05-26 — trying previous weekday...
Skipping SPX for 2024-05-24 — already in DB
       current_return last_week_return last_month_return  current_rank  \
ticker
PLTR           498.5%             3.1%            486.9%           1.0
GEV            181.6%             3.4%            161.7%           2.0
AXON           174.5%             4.3%            156.1%           3.0
HWM            123.9%             3.9%             94.9%           4.0
VST            121.6%             5.1%             54.9%           5.0
...               ...              ...               ...           ...
HAL            -39.3%            -7.4%            -44.9%         491.0
SMCI           -40.7%            10.8%            -54.6%         494.0
AES            -42.8%             2.8%            -52.2%         495.0
ENPH           -58.2%            18.2%            -68.3%         499.0
MRNA           -77.5%             8.4%            -84.2%         500.0

        last_month_rank  rank_change
ticker
PLTR                1.0          0.0
GEV                 2.0          0.0
AXON                3.0          0.0
HWM                 5.0          1.0
VST                24.0         19.0
...                 ...          ...
HAL               492.0          1.0
SMCI              497.0          3.0
AES               496.0          1.0
ENPH              499.0          0.0
MRNA              500.0          0.0

[245 rows x 6 columns]
current_return        object
last_week_return      object
last_month_return     object
current_rank         float64
last_month_rank      float64
rank_change          float64
dtype: object
       current_return last_week_return last_month_return  current_rank  \
ticker
PLTR           498.5%             3.1%            486.9%           1.0
GEV            181.6%             3.4%            161.7%           2.0
AXON           174.5%             4.3%            156.1%           3.0
HWM            123.9%             3.9%             94.9%           4.0
VST            121.6%             5.1%             54.9%           5.0

        last_month_rank  rank_change
ticker
PLTR                1.0          0.0
GEV                 2.0          0.0
AXON                3.0          0.0
HWM                 5.0          1.0
VST                24.0         19.0
✅ Stored top 10 picks for 2025-06-27
🔍 Processing PLTR (1/10)
  📦 Recent news articles: 5
  ✅ News already fresh — skipping API call.
🔍 Processing GEV (2/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing AXON (3/10)
  📦 Recent news articles: 1
  ✅ News already fresh — skipping API call.
🔍 Processing HWM (4/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing VST (5/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing DASH (6/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing TPR (7/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing JBL (8/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing RCL (9/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing FTNT (10/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
  ticker current_return last_week_return
0   PLTR         498.5%             3.1%
1    GEV         181.6%             3.4%
2   AXON         174.5%             4.3%
3    HWM         123.9%             3.9%
4    VST         121.6%             5.1%
[0.031, 0.034, 0.043, 0.039, 0.051]
📅 Resolved VOO dates: {'current': '2025-06-26', 'one_year_ago': '2024-06-26', 'one_week_ago': '2025-06-18'}
📈 Retrieved VOO prices: {'2024-06-26': 503.07, '2025-06-18': 549.24, '2025-06-26': 564.15}
🔎 All compare tickers: ['GILD', 'PLTR', 'RCL', 'GEV', 'PM', 'TPR', 'VST', 'DASH', 'FTNT', 'HWM', 'JBL', 'AXON']
🔎 Available price tickers: ['AXON', 'DASH', 'FTNT', 'GEV', 'GILD', 'HWM', 'JBL', 'PLTR', 'PM', 'RCL', 'TPR', 'VST']
🔎 Tickers in report: ['PLTR', 'GEV', 'AXON', 'HWM', 'VST', 'DASH', 'TPR', 'JBL', 'RCL', 'FTNT']
🔎 Prices dict keys: ['AXON', 'DASH', 'FTNT', 'GEV', 'GILD', 'HWM', 'JBL', 'PLTR', 'PM', 'RCL']
✅ Summary HTML block:
 <p><strong>Benchmark (VOO):</strong> $564.15 (<span style="color:#006400;">+12.1%</span> last 12M, <span style="color:#006400;">+2.7%</span> last week)</p><h3>Summary of Changes</h3><p>PLTR – $144.25 (<span style="color:#006400;">+498.5%</span> last 12M, <span style="color:#006400;">+3.1%</span> last week)<br>GEV – $506.81 (<span style="color:#006400;">+181.6%</span> last 12M, <span style="color:#006400;">+3.4%</span> last week)<br>AXON – $803.95 (<span style="color:#006400;">+174.5%</span> last
🧪 DEBUG: Jinja context types and sample values:
  summary_html: <class 'str'> <p><strong>Benchmark (VOO):</strong> $564.15 (<span style="color:#006400;">+12.1%</span> last 12M, <span style="color:#006400;">+2.7%</span> last week)</p><h3>Summary of Changes</h3><p>PLTR – $144.25
  formatted_date: <class 'str'> June 27, 2025
  voo_now: <class 'numpy.float64'> 564.15
  enriched (length): 10
    First stock:
      ticker: <class 'str'> PLTR
      price: <class 'str'> 144.25
      current_return: <class 'str'> 498.5%
      last_month_return: <class 'str'> 486.9%
      rank_change: <class 'float'> 0.0
✅ Report written: /Users/zacseidel/Documents/GitHub/momentum-screener/reports/momentum_2025-06-27.html

Collecting functools
  Downloading functools-0.5.tar.gz (4.9 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: functools
  DEPRECATION: Building 'functools' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'functools'. Discussion can be found at https://github.com/pypa/pip/issues/6334
  Building wheel for functools (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [72 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-x86_64-3.9
      copying functools.py -> build/lib.macosx-10.9-x86_64-3.9
      running build_ext
      building '_functools' extension
      creating build/temp.macosx-10.9-x86_64-3.9
      creating build/temp.macosx-10.9-x86_64-3.9/src
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/zacseidel/opt/anaconda3/include -arch x86_64 -I/Users/zacseidel/opt/anaconda3/include -fPIC -O2 -isystem /Users/zacseidel/opt/anaconda3/include -arch x86_64 -I/Users/zacseidel/opt/anaconda3/include/python3.9 -c src/compose.c -o build/temp.macosx-10.9-x86_64-3.9/src/compose.o
      src/compose.c:96:6: error: no member named 'ob_type' in 'struct compose'
         96 |         co->ob_type->tp_free(co);
            |         ~~  ^
      src/compose.c:137:6: error: call to undeclared function 'PyString_FromFormat'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        137 |         s = PyString_FromFormat("<composition on %s at %p>",
            |             ^
      src/compose.c:137:6: note: did you mean 'PyBytes_FromFormat'?
      /Users/zacseidel/opt/anaconda3/include/python3.9/bytesobject.h:42:24: note: 'PyBytes_FromFormat' declared here
         42 | PyAPI_FUNC(PyObject *) PyBytes_FromFormat(const char*, ...)
            |                        ^
      src/compose.c:138:6: error: call to undeclared function 'PyString_AsString'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        138 |             PyString_AsString(grepr), (void *)co);
            |             ^
      src/compose.c:137:4: error: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
        137 |         s = PyString_FromFormat("<composition on %s at %p>",
            |           ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        138 |             PyString_AsString(grepr), (void *)co);
            |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      src/compose.c:144:2: warning: suggest braces around initialization of subobject [-Wmissing-braces]
        144 |         PyObject_HEAD_INIT(NULL)
            |         ^~~~~~~~~~~~~~~~~~~~~~~~
      /Users/zacseidel/opt/anaconda3/include/python3.9/object.h:86:5: note: expanded from macro 'PyObject_HEAD_INIT'
         86 |     1, type },
            |     ^~~~~~~
      src/compose.c:146:2: error: incompatible pointer to integer conversion initializing 'Py_ssize_t' (aka 'long') with an expression of type 'char[8]' [-Wint-conversion]
        146 |         "compose",                      /* tp_name */
            |         ^~~~~~~~~
      src/compose.c:150:2: error: incompatible pointer to integer conversion initializing 'Py_ssize_t' (aka 'long') with an expression of type 'destructor' (aka 'void (*)(struct _object *)') [-Wint-conversion]
        150 |         (destructor)compose_dealloc,    /* tp_dealloc */
            |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      src/compose.c:155:2: warning: incompatible pointer types initializing 'PyNumberMethods *' with an expression of type 'reprfunc' (aka 'struct _object *(*)(struct _object *)') [-Wincompatible-pointer-types]
        155 |         (reprfunc)compose_repr,         /* tp_repr */
            |         ^~~~~~~~~~~~~~~~~~~~~~
      src/compose.c:160:2: error: incompatible function pointer types initializing 'reprfunc' (aka 'struct _object *(*)(struct _object *)') with an expression of type 'ternaryfunc' (aka 'struct _object *(*)(struct _object *, struct _object *, struct _object *)') [-Wincompatible-function-pointer-types]
        160 |         (ternaryfunc)compose_call,      /* tp_call */
            |         ^~~~~~~~~~~~~~~~~~~~~~~~~
      src/compose.c:165:2: error: incompatible integer to pointer conversion initializing 'const char *' with an expression of type 'unsigned long' [-Wint-conversion]
        165 |         Py_TPFLAGS_DEFAULT | Py_TPFLAGS_HAVE_GC |
            |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        166 |                 Py_TPFLAGS_BASETYPE,    /* tp_flags */
            |                 ~~~~~~~~~~~~~~~~~~~
      /Users/zacseidel/opt/anaconda3/include/python3.9/object.h:350:29: note: expanded from macro 'Py_TPFLAGS_DEFAULT'
        350 | #define Py_TPFLAGS_DEFAULT  ( \
            |                             ^
      src/compose.c:167:2: warning: incompatible pointer types initializing 'traverseproc' (aka 'int (*)(struct _object *, int (*)(struct _object *, void *), void *)') with an expression of type 'const char[372]' [-Wincompatible-pointer-types]
        167 |         compose_doc,                    /* tp_doc */
            |         ^~~~~~~~~~~
      src/compose.c:168:2: error: incompatible function pointer types initializing 'inquiry' (aka 'int (*)(struct _object *)') with an expression of type 'traverseproc' (aka 'int (*)(struct _object *, int (*)(struct _object *, void *), void *)') [-Wincompatible-function-pointer-types]
        168 |         (traverseproc)compose_traverse, /* tp_traverse */
            |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      src/compose.c:179:2: error: incompatible function pointer types initializing 'descrsetfunc' (aka 'int (*)(struct _object *, struct _object *, struct _object *)') with an expression of type 'PyObject *(PyObject *, PyObject *)' (aka 'struct _object *(struct _object *, struct _object *)') [-Wincompatible-function-pointer-types]
        179 |         PyMethod_New,                   /* tp_descr_get */
            |         ^~~~~~~~~~~~
      src/compose.c:184:2: error: incompatible function pointer types initializing 'freefunc' (aka 'void (*)(void *)') with an expression of type 'PyObject *(PyTypeObject *, PyObject *, PyObject *)' (aka 'struct _object *(struct _typeobject *, struct _object *, struct _object *)') [-Wincompatible-function-pointer-types]
        184 |         compose_new,                    /* tp_new */
            |         ^~~~~~~~~~~
      src/compose.c:185:2: error: incompatible function pointer types initializing 'inquiry' (aka 'int (*)(struct _object *)') with an expression of type 'void (void *)' [-Wincompatible-function-pointer-types]
        185 |         PyObject_GC_Del,                /* tp_free */
            |         ^~~~~~~~~~~~~~~
      3 warnings and 12 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for functools
  Running setup.py clean for functools
Failed to build functools
ERROR: Failed to build installable wheels for some pyproject.toml based projects (functools)

In [ ]:
# Example: Generate reports for 3 recent Fridays
generate_html_for_date("2025-05-02")
generate_html_for_date("2025-05-09")
generate_html_for_date("2025-05-16")
generate_html_for_date("2025-05-23")

⏳ Generating report for 2025-05-02
Skipping 2025-05-01 — already in DB
Skipping SPX for 2025-05-01 — already in DB
Skipping 2024-05-01 — already in DB
Skipping SPX for 2024-05-01 — already in DB
Skipping 2025-04-01 — already in DB
Skipping SPX for 2025-04-01 — already in DB
Skipping 2024-04-01 — already in DB
Skipping SPX for 2024-04-01 — already in DB
✅ Stored top 10 picks for 2025-05-02
🔍 Processing PLTR (1/10)
  📦 Recent news articles: 2
  ✅ News already fresh — skipping API call.
🔍 Processing NFLX (2/10)
  📦 Recent news articles: 4
  ✅ News already fresh — skipping API call.
🔍 Processing AXON (3/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing VST (4/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing TPR (5/10)
  📦 Recent news articles: 1
  ✅ News already fresh — skipping API call.
🔍 Processing PM (6/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing FICO (7/10)
  📦 Recent news articles: 1
  ✅ News already fresh — skipping API call.
🔍 Processing WMT (8/10)
  📦 Recent news articles: 1
  ✅ News already fresh — skipping API call.
🔍 Processing TTWO (9/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing FTNT (10/10)
  📦 Recent news articles: 1
  ✅ News already fresh — skipping API call.
📅 Resolved VOO dates: {'current': '2025-05-01', 'one_year_ago': '2024-05-01'}
📈 Retrieved VOO prices: {'2024-05-01': 459.93, '2025-05-01': 513.35}
🔎 All compare tickers: ['WMT', 'TTWO', 'TPR', 'VST', 'PM', 'AXON', 'FICO', 'FTNT', 'PLTR', 'NFLX']
🔎 Available price tickers: ['AXON', 'FICO', 'FTNT', 'NFLX', 'PLTR', 'PM', 'TPR', 'TTWO', 'VST', 'WMT']
🔎 Tickers in report: ['PLTR', 'NFLX', 'AXON', 'VST', 'TPR', 'PM', 'FICO', 'WMT', 'TTWO', 'FTNT']
🔎 Prices dict keys: ['AXON', 'FICO', 'FTNT', 'NFLX', 'PLTR', 'PM', 'TPR', 'TTWO', 'VST', 'WMT']
✅ Summary HTML block:
 <p><strong>Benchmark (VOO):</strong> $513.35 (+11.6% last 12M)</p><h3>Summary of Changes</h3><p><b>PLTR – $116.20 (425.3% last 12M)</b><br><b>NFLX – $1133.47 (105.4% last 12M)</b><br><b>AXON – $621.10 (99.3% last 12M)</b><br><b>VST – $137.30 (78.6% last 12M)</b><br><b>TPR – $70.49 (78.5% last 12M)</b><br><b>PM – $170.05 (77.0% last 12M)</b><br><b>FICO – $2001.68 (75.5% last 12M)</b><br><b>WMT – $97.41 (65.5% last 12M)</b><br><b>TTWO – $235.17 (64.8% last 12M)</b><br><b>FTNT – $104.21 (64.0% last
🧪 DEBUG: Jinja context types and sample values:
  summary_html: <class 'str'> <p><strong>Benchmark (VOO):</strong> $513.35 (+11.6% last 12M)</p><h3>Summary of Changes</h3><p><b>PLTR – $116.20 (425.3% last 12M)</b><br><b>NFLX – $1133.47 (105.4% last 12M)</b><br><b>AXON – $621.10
  formatted_date: <class 'str'> May 02, 2025
  voo_now: <class 'numpy.float64'> 513.35
  voo_return: <class 'numpy.float64'> 0.11614810949492327
  enriched (length): 10
    First stock:
      ticker: <class 'str'> PLTR
      price: <class 'str'> 116.20
      current_return: <class 'str'> 425.3%
      last_month_return: <class 'str'> 270.4%
      rank_change: <class 'float'> 0.0
✅ Report written: /Users/zacseidel/Documents/GitHub/momentum-screener/reports/momentum_2025-05-02.html
⏳ Generating report for 2025-05-09
Skipping 2025-05-08 — already in DB
Skipping SPX for 2025-05-08 — already in DB
Skipping 2024-05-08 — already in DB
Skipping SPX for 2024-05-08 — already in DB
Skipping 2025-04-08 — already in DB
Skipping SPX for 2025-04-08 — already in DB
Skipping 2024-04-08 — already in DB
Skipping SPX for 2024-04-08 — already in DB
✅ Stored top 10 picks for 2025-05-09
🔍 Processing PLTR (1/10)
  📦 Recent news articles: 2
  ✅ News already fresh — skipping API call.
🔍 Processing GEV (2/10)
  📦 Recent news articles: 1
  ✅ News already fresh — skipping API call.
🔍 Processing TPL (3/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing AXON (4/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing TPR (5/10)
  📦 Recent news articles: 1
  ✅ News already fresh — skipping API call.
🔍 Processing NFLX (6/10)
  📦 Recent news articles: 4
  ✅ News already fresh — skipping API call.
🔍 Processing TKO (7/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing VRSN (8/10)
  📦 Recent news articles: 1
  ✅ News already fresh — skipping API call.
🔍 Processing FICO (9/10)
  📦 Recent news articles: 1
  ✅ News already fresh — skipping API call.
🔍 Processing RCL (10/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
📅 Resolved VOO dates: {'current': '2025-05-08', 'one_year_ago': '2024-05-08'}
📈 Retrieved VOO prices: {'2024-05-08': 475.42, '2025-05-08': 519.34}
🔎 All compare tickers: ['WMT', 'TPL', 'VRSN', 'VST', 'PM', 'FICO', 'FTNT', 'PLTR', 'TKO', 'TTWO', 'TPR', 'RCL', 'GEV', 'AXON', 'NFLX']
🔎 Available price tickers: ['AXON', 'FICO', 'FTNT', 'GEV', 'NFLX', 'PLTR', 'PM', 'RCL', 'TKO', 'TPL', 'TPR', 'TTWO', 'VRSN', 'VST', 'WMT']
🔎 Tickers in report: ['PLTR', 'GEV', 'TPL', 'AXON', 'TPR', 'NFLX', 'TKO', 'VRSN', 'FICO', 'RCL']
🔎 Prices dict keys: ['AXON', 'FICO', 'FTNT', 'GEV', 'NFLX', 'PLTR', 'PM', 'RCL', 'TKO', 'TPL']
✅ Summary HTML block:
 <p><strong>Benchmark (VOO):</strong> $519.34 (+9.2% last 12M)</p><h3>Summary of Changes</h3><p>PLTR – $119.15 (452.6% last 12M)<br><b>GEV – $394.00 (140.2% last 12M)</b><br><b>TPL – $1287.49 (128.5% last 12M)</b><br>AXON – $686.83 (120.2% last 12M)<br>TPR – $77.54 (98.9% last 12M)<br>NFLX – $1144.43 (87.8% last 12M)<br><b>TKO – $168.96 (71.9% last 12M)</b><br><b>VRSN – $285.21 (69.2% last 12M)</b><br>FICO – $2105.76 (68.3% last 12M)<br><b>RCL – $232.84 (64.3% last 12M)</b><br><s>FTNT – $97.74 (—
🧪 DEBUG: Jinja context types and sample values:
  summary_html: <class 'str'> <p><strong>Benchmark (VOO):</strong> $519.34 (+9.2% last 12M)</p><h3>Summary of Changes</h3><p>PLTR – $119.15 (452.6% last 12M)<br><b>GEV – $394.00 (140.2% last 12M)</b><br><b>TPL – $1287.49 (128.5% l
  formatted_date: <class 'str'> May 09, 2025
  voo_now: <class 'numpy.float64'> 519.34
  voo_return: <class 'numpy.float64'> 0.09238147322367585
  enriched (length): 10
    First stock:
      ticker: <class 'str'> PLTR
      price: <class 'str'> 119.15
      current_return: <class 'str'> 452.6%
      last_month_return: <class 'str'> 236.2%
      rank_change: <class 'float'> 0.0
✅ Report written: /Users/zacseidel/Documents/GitHub/momentum-screener/reports/momentum_2025-05-09.html
⏳ Generating report for 2025-05-16
Skipping 2025-05-15 — already in DB
Skipping SPX for 2025-05-15 — already in DB
Skipping 2024-05-15 — already in DB
Skipping SPX for 2024-05-15 — already in DB
Skipping 2025-04-15 — already in DB
Skipping SPX for 2025-04-15 — already in DB
Skipping 2024-04-15 — already in DB
Skipping SPX for 2024-04-15 — already in DB
✅ Stored top 10 picks for 2025-05-16
🔍 Processing PLTR (1/10)
  📦 Recent news articles: 2
  ✅ News already fresh — skipping API call.
🔍 Processing GEV (2/10)
  📦 Recent news articles: 1
  ✅ News already fresh — skipping API call.
🔍 Processing AXON (3/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing TPL (4/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing TSLA (5/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing TPR (6/10)
  📦 Recent news articles: 1
  ✅ News already fresh — skipping API call.
🔍 Processing NFLX (7/10)
  📦 Recent news articles: 4
  ✅ News already fresh — skipping API call.
🔍 Processing NRG (8/10)
  📦 Recent news articles: 1
  ✅ News already fresh — skipping API call.
🔍 Processing PODD (9/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing RCL (10/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
📅 Resolved VOO dates: {'current': '2025-05-16', 'one_year_ago': '2024-05-15'}
📈 Retrieved VOO prices: {'2024-05-15': 486.9, '2025-05-16': 546.26}
🔎 All compare tickers: ['TPL', 'VRSN', 'FICO', 'NRG', 'PLTR', 'TSLA', 'TKO', 'TPR', 'RCL', 'GEV', 'AXON', 'PODD', 'NFLX']
🔎 Available price tickers: ['AXON', 'FICO', 'GEV', 'NFLX', 'NRG', 'PLTR', 'PODD', 'RCL', 'TKO', 'TPL', 'TPR', 'TSLA', 'VRSN']
🔎 Tickers in report: ['PLTR', 'GEV', 'AXON', 'TPL', 'TSLA', 'TPR', 'NFLX', 'NRG', 'PODD', 'RCL']
🔎 Prices dict keys: ['AXON', 'FICO', 'GEV', 'NFLX', 'NRG', 'PLTR', 'PODD', 'RCL', 'TKO', 'TPL']
✅ Summary HTML block:
 <p><strong>Benchmark (VOO):</strong> $546.26 (+12.2% last 12M)</p><h3>Summary of Changes</h3><p>PLTR – $128.12 (491.2% last 12M)<br>GEV – $426.97 (154.3% last 12M)<br>AXON – $728.39 (147.8% last 12M)<br>TPL – $1417.10 (135.6% last 12M)<br><b>TSLA – $342.82 (97.0% last 12M)</b><br>TPR – $83.24 (95.1% last 12M)<br>NFLX – $1177.98 (92.0% last 12M)<br><b>NRG – $155.02 (83.5% last 12M)</b><br><b>PODD – $322.02 (78.3% last 12M)</b><br>RCL – $250.11 (77.8% last 12M)<br><s>FICO – $2180.44 (— last 12M)</
🧪 DEBUG: Jinja context types and sample values:
  summary_html: <class 'str'> <p><strong>Benchmark (VOO):</strong> $546.26 (+12.2% last 12M)</p><h3>Summary of Changes</h3><p>PLTR – $128.12 (491.2% last 12M)<br>GEV – $426.97 (154.3% last 12M)<br>AXON – $728.39 (147.8% last 12M)<
  formatted_date: <class 'str'> May 16, 2025
  voo_now: <class 'numpy.float64'> 546.26
  voo_return: <class 'numpy.float64'> 0.12191415074964063
  enriched (length): 10
    First stock:
      ticker: <class 'str'> PLTR
      price: <class 'str'> 128.12
      current_return: <class 'str'> 491.2%
      last_month_return: <class 'str'> 349.3%
      rank_change: <class 'float'> 0.0
✅ Report written: /Users/zacseidel/Documents/GitHub/momentum-screener/reports/momentum_2025-05-16.html

https://api.polygon.io/v2/aggs/ticker/AAPL/range/1/day/2025-05-10/2025-05-10?adjusted=true&apiKey=X7QL9PhUOMpuV5SGf7Vnqfa4NPLRsKxl

In [37]:


generate_html_for_date("2024-07-12")
generate_html_for_date("2024-07-19")
generate_html_for_date("2024-07-26")
generate_html_for_date("2024-08-02")
generate_html_for_date("2024-08-09")
generate_html_for_date("2024-08-16")
generate_html_for_date("2024-08-23")
generate_html_for_date("2024-08-30")
generate_html_for_date("2024-09-06")
generate_html_for_date("2024-09-13")
generate_html_for_date("2024-09-20")
generate_html_for_date("2024-09-27")
generate_html_for_date("2024-10-04")
generate_html_for_date("2024-10-11")
generate_html_for_date("2024-10-18")
generate_html_for_date("2024-10-25")
generate_html_for_date("2024-11-01")
generate_html_for_date("2024-11-08")
generate_html_for_date("2024-11-15")
generate_html_for_date("2024-11-22")
generate_html_for_date("2024-11-29")
generate_html_for_date("2024-12-06")
generate_html_for_date("2024-12-13")
generate_html_for_date("2024-12-20")
generate_html_for_date("2024-12-27")        




generate_html_for_date("2025-01-03")
generate_html_for_date("2025-01-10")
generate_html_for_date("2025-01-17")
generate_html_for_date("2025-01-24")
generate_html_for_date("2025-01-31")
generate_html_for_date("2025-02-07")
generate_html_for_date("2025-02-14")
generate_html_for_date("2025-02-21")
generate_html_for_date("2025-02-28")
generate_html_for_date("2025-03-07")
generate_html_for_date("2025-03-14")
generate_html_for_date("2025-03-21")
generate_html_for_date("2025-03-28")
generate_html_for_date("2025-04-04")
generate_html_for_date("2025-04-11")
generate_html_for_date("2025-04-18")
generate_html_for_date("2025-04-25")
generate_html_for_date("2025-05-02")
generate_html_for_date("2025-05-09")
generate_html_for_date("2025-05-16")
generate_html_for_date("2025-05-23")

⏳ Generating report for 2024-07-12
Fetching grouped prices for 2024-07-11...
Stored 10551 rows for 2024-07-11
Fetching SPX price for 2024-07-11...
✅ Stored SPX price for 2024-07-11: $511.39
Fetching grouped prices for 2023-07-11...
Stored 10596 rows for 2023-07-11
Fetching SPX price for 2023-07-11...
✅ Stored SPX price for 2023-07-11: $406.56
Fetching grouped prices for 2024-06-11...
Stored 10519 rows for 2024-06-11
Fetching SPX price for 2024-06-11...
✅ Stored SPX price for 2024-06-11: $493.53
Fetching grouped prices for 2023-06-11...
No data for 2023-06-11 — trying previous weekday...
Fetching grouped prices for 2023-06-09...
Stored 10577 rows for 2023-06-09
Fetching SPX price for 2023-06-11...
No SPX data for 2023-06-11 — trying previous weekday...
Fetching SPX price for 2023-06-09...
✅ Stored SPX price for 2023-06-09: $395.03
✅ Stored top 10 picks for 2024-07-12
       current_return last_month_return  current_rank  last_month_rank  \
ticker
VST            245.4%            267.5%           1.0              1.0
SMCI           228.2%            193.4%           2.0              3.0
DELL           152.5%            176.5%           4.0              4.0
CRWD           145.7%            157.2%           5.0              5.0
WSM            137.5%            138.4%           6.0              6.0
...               ...               ...           ...              ...
PODD           -27.9%            -32.1%         479.0            485.0
PARA           -30.3%            -31.4%         483.0            483.0
BF.B           -34.1%            -32.9%         486.0            486.0
BMY            -35.1%            -33.6%         488.0            488.0
PAYC           -57.4%            -52.9%         492.0            492.0

        rank_change
ticker
VST             0.0
SMCI            1.0
DELL            0.0
CRWD            0.0
WSM             0.0
...             ...
PODD            6.0
PARA            0.0
BF.B            0.0
BMY             0.0
PAYC            0.0

[257 rows x 5 columns]
🔍 Processing VST (1/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing SMCI (2/10)
  📦 Recent news articles: 0
  🧠 Fetching metadata...
  ⏳ Sleeping for rate limit...
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing DELL (3/10)
  📦 Recent news articles: 0
  🧠 Fetching metadata...
  ⏳ Sleeping for rate limit...
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing CRWD (4/10)
  📦 Recent news articles: 0
  🧠 Fetching metadata...
  ⏳ Sleeping for rate limit...
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing WSM (5/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing CEG (6/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing ANET (7/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing LLY (8/10)
  📦 Recent news articles: 0
  🧠 Fetching metadata...
  ⏳ Sleeping for rate limit...
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing WDC (9/10)
  📦 Recent news articles: 0
  🧠 Fetching metadata...
  ⏳ Sleeping for rate limit...
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing FICO (10/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
📅 Resolved VOO dates: {'current': '2024-07-11', 'one_year_ago': '2023-07-11'}
📈 Retrieved VOO prices: {'2023-07-11': 406.56, '2024-07-11': 511.39}
🔎 All compare tickers: ['CEG', 'LLY', 'CRWD', 'SMCI', 'DELL', 'VST', 'FICO', 'WDC', 'WSM', 'ANET']
🔎 Available price tickers: ['ANET', 'CEG', 'CRWD', 'DELL', 'FICO', 'LLY', 'SMCI', 'VST', 'WDC', 'WSM']
🔎 Tickers in report: ['VST', 'SMCI', 'DELL', 'CRWD', 'WSM', 'CEG', 'ANET', 'LLY', 'WDC', 'FICO']
🔎 Prices dict keys: ['ANET', 'CEG', 'CRWD', 'DELL', 'FICO', 'LLY', 'SMCI', 'VST', 'WDC', 'WSM']
✅ Summary HTML block:
 <p><strong>Benchmark (VOO):</strong> $511.39 (+25.8% last 12M)</p><h3>Summary of Changes</h3><p><i>VST – $91.61 (245.4% last 12M)</i><br><i>SMCI – $88.92 (228.2% last 12M)</i><br><i>DELL – $140.72 (152.5% last 12M)</i><br><i>CRWD – $370.43 (145.7% last 12M)</i><br><i>WSM – $153.58 (137.5% last 12M)</i><br><i>CEG – $216.84 (129.8% last 12M)</i><br><i>ANET – $89.90 (124.5% last 12M)</i><br><i>LLY – $934.14 (112.6% last 12M)</i><br><i>WDC – $77.84 (102.9% last 12M)</i><br><i>FICO – $1567.52 (93.9%
🧪 DEBUG: Jinja context types and sample values:
  summary_html: <class 'str'> <p><strong>Benchmark (VOO):</strong> $511.39 (+25.8% last 12M)</p><h3>Summary of Changes</h3><p><i>VST – $91.61 (245.4% last 12M)</i><br><i>SMCI – $88.92 (228.2% last 12M)</i><br><i>DELL – $140.72 (15
  formatted_date: <class 'str'> July 12, 2024
  voo_now: <class 'numpy.float64'> 511.39
  voo_return: <class 'numpy.float64'> 0.2578463203463204
  enriched (length): 10
    First stock:
      ticker: <class 'str'> VST
      price: <class 'str'> 91.61
      current_return: <class 'str'> 245.4%
      last_month_return: <class 'str'> 267.5%
      rank_change: <class 'float'> 0.0
✅ Report written: /Users/zacseidel/Documents/GitHub/momentum-screener/reports/momentum_2024-07-12.html
⏳ Generating report for 2024-07-19
Fetching grouped prices for 2024-07-18...
Stored 10571 rows for 2024-07-18
Fetching SPX price for 2024-07-18...
✅ Stored SPX price for 2024-07-18: $507.94
Fetching grouped prices for 2023-07-18...
Stored 10601 rows for 2023-07-18
Fetching SPX price for 2023-07-18...
✅ Stored SPX price for 2023-07-18: $417.35
Fetching grouped prices for 2024-06-18...
Stored 10542 rows for 2024-06-18
Fetching SPX price for 2024-06-18...
✅ Stored SPX price for 2024-06-18: $504.28
Fetching grouped prices for 2023-06-18...
No data for 2023-06-18 — trying previous weekday...
Fetching grouped prices for 2023-06-16...
Stored 10607 rows for 2023-06-16
Fetching SPX price for 2023-06-18...
No SPX data for 2023-06-18 — trying previous weekday...
Fetching SPX price for 2023-06-16...
✅ Stored SPX price for 2023-06-16: $405.25
✅ Stored top 10 picks for 2024-07-19
       current_return last_month_return  current_rank  last_month_rank  \
ticker
VST            185.8%            249.5%           1.0              2.0
NVDA           155.0%            217.6%           2.0              3.0
DELL           132.8%            200.3%           4.0              4.0
WSM            130.8%            156.6%           5.0              5.0
CRWD           124.3%            151.1%           6.0              6.0
...               ...               ...           ...              ...
MTCH           -27.0%            -27.9%         476.0            477.0
BMY            -31.6%            -38.3%         483.0            487.0
WBD            -33.3%            -45.4%         485.0            489.0
PAYC           -57.4%            -55.8%         492.0            492.0
ALB            -60.4%            -56.4%         493.0            493.0

        rank_change
ticker
VST             1.0
NVDA            1.0
DELL            0.0
WSM             0.0
CRWD            0.0
...             ...
MTCH            1.0
BMY             4.0
WBD             4.0
PAYC            0.0
ALB             0.0

[260 rows x 5 columns]
🔍 Processing VST (1/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing NVDA (2/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing DELL (3/10)
  📦 Recent news articles: 1
  ✅ News already fresh — skipping API call.
🔍 Processing WSM (4/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing CRWD (5/10)
  📦 Recent news articles: 5
  ✅ News already fresh — skipping API call.
🔍 Processing NRG (6/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing ANET (7/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing LLY (8/10)
  📦 Recent news articles: 5
  ✅ News already fresh — skipping API call.
🔍 Processing FICO (9/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing PGR (10/10)
  📦 Recent news articles: 0
  🧠 Fetching metadata...
  ⏳ Sleeping for rate limit...
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
📅 Resolved VOO dates: {'current': '2024-07-18', 'one_year_ago': '2023-07-18'}
📈 Retrieved VOO prices: {'2023-07-18': 417.35, '2024-07-18': 507.94}
🔎 All compare tickers: ['CEG', 'CRWD', 'DELL', 'PGR', 'WSM', 'WDC', 'NVDA', 'LLY', 'NRG', 'VST', 'SMCI', 'FICO', 'ANET']
🔎 Available price tickers: ['ANET', 'CEG', 'CRWD', 'DELL', 'FICO', 'LLY', 'NRG', 'NVDA', 'PGR', 'SMCI', 'VST', 'WDC', 'WSM']
🔎 Tickers in report: ['VST', 'NVDA', 'DELL', 'WSM', 'CRWD', 'NRG', 'ANET', 'LLY', 'FICO', 'PGR']
🔎 Prices dict keys: ['ANET', 'CEG', 'CRWD', 'DELL', 'FICO', 'LLY', 'NRG', 'NVDA', 'PGR', 'SMCI']
✅ Summary HTML block:
 <p><strong>Benchmark (VOO):</strong> $507.94 (+21.7% last 12M)</p><h3>Summary of Changes</h3><p>VST – $76.55 (185.8% last 12M)<br><i>NVDA – $121.09 (155.0% last 12M)</i><br>DELL – $125.34 (132.8% last 12M)<br>WSM – $148.77 (130.8% last 12M)<br>CRWD – $343.05 (124.3% last 12M)<br><i>NRG – $73.63 (99.2% last 12M)</i><br>ANET – $83.16 (91.7% last 12M)<br>LLY – $848.90 (88.1% last 12M)<br>FICO – $1584.76 (87.8% last 12M)<br><i>PGR – $224.53 (87.4% last 12M)</i><br><s>CEG – $187.28 (— last 12M)</s><b
🧪 DEBUG: Jinja context types and sample values:
  summary_html: <class 'str'> <p><strong>Benchmark (VOO):</strong> $507.94 (+21.7% last 12M)</p><h3>Summary of Changes</h3><p>VST – $76.55 (185.8% last 12M)<br><i>NVDA – $121.09 (155.0% last 12M)</i><br>DELL – $125.34 (132.8% last
  formatted_date: <class 'str'> July 19, 2024
  voo_now: <class 'numpy.float64'> 507.94
  voo_return: <class 'numpy.float64'> 0.2170600215646339
  enriched (length): 10
    First stock:
      ticker: <class 'str'> VST
      price: <class 'str'> 76.55
      current_return: <class 'str'> 185.8%
      last_month_return: <class 'str'> 249.5%
      rank_change: <class 'float'> 1.0
✅ Report written: /Users/zacseidel/Documents/GitHub/momentum-screener/reports/momentum_2024-07-19.html
⏳ Generating report for 2024-07-26
Fetching grouped prices for 2024-07-25...
Stored 10544 rows for 2024-07-25
Fetching SPX price for 2024-07-25...
✅ Stored SPX price for 2024-07-25: $494.78
Fetching grouped prices for 2023-07-25...
Stored 10610 rows for 2023-07-25
Fetching SPX price for 2023-07-25...
✅ Stored SPX price for 2023-07-25: $418.56
Fetching grouped prices for 2024-06-25...
Stored 10554 rows for 2024-06-25
Fetching SPX price for 2024-06-25...
✅ Stored SPX price for 2024-06-25: $502.51
Fetching grouped prices for 2023-06-25...
No data for 2023-06-25 — trying previous weekday...
Fetching grouped prices for 2023-06-23...
Stored 10555 rows for 2023-06-23
Fetching SPX price for 2023-06-25...
No SPX data for 2023-06-25 — trying previous weekday...
Fetching SPX price for 2023-06-23...
✅ Stored SPX price for 2023-06-23: $399.61
✅ Stored top 10 picks for 2024-07-26
       current_return last_month_return  current_rank  last_month_rank  \
ticker
VST            150.5%            256.2%           1.0              2.0
NVDA           145.8%            198.7%           2.0              3.0
WSM            123.6%            145.1%           3.0              7.0
KKR             91.5%            100.4%           6.0             12.0
GDDY            91.0%             95.1%           7.0             14.0
...               ...               ...           ...              ...
ENPH           -34.5%            -35.8%         483.0            488.0
WBD            -36.2%            -38.6%         487.0            489.0
EL             -44.0%            -40.7%         490.0            490.0
PAYC           -54.0%            -53.8%         492.0            492.0
ALB            -57.2%            -57.9%         493.0            493.0

        rank_change
ticker
VST             1.0
NVDA            1.0
WSM             4.0
KKR             6.0
GDDY            7.0
...             ...
ENPH            5.0
WBD             2.0
EL              0.0
PAYC            0.0
ALB             0.0

[258 rows x 5 columns]
🔍 Processing VST (1/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing NVDA (2/10)
  📦 Recent news articles: 5
  ✅ News already fresh — skipping API call.
🔍 Processing WSM (3/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing KKR (4/10)
  📦 Recent news articles: 0
  🧠 Fetching metadata...
  ⏳ Sleeping for rate limit...
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing GDDY (5/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing NRG (6/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing FICO (7/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing ERIE (8/10)
  📦 Recent news articles: 0
  🧠 Fetching metadata...
  ⏳ Sleeping for rate limit...
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing LLY (9/10)
  📦 Recent news articles: 5
  ✅ News already fresh — skipping API call.
🔍 Processing STX (10/10)
  📦 Recent news articles: 0
  🧠 Fetching metadata...
  ⏳ Sleeping for rate limit...
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
📅 Resolved VOO dates: {'current': '2024-07-25', 'one_year_ago': '2023-07-25'}
📈 Retrieved VOO prices: {'2023-07-25': 418.56, '2024-07-25': 494.78}
🔎 All compare tickers: ['CRWD', 'DELL', 'PGR', 'WSM', 'ERIE', 'NVDA', 'LLY', 'NRG', 'VST', 'KKR', 'FICO', 'GDDY', 'ANET', 'STX']
🔎 Available price tickers: ['ANET', 'CRWD', 'DELL', 'ERIE', 'FICO', 'GDDY', 'KKR', 'LLY', 'NRG', 'NVDA', 'PGR', 'STX', 'VST', 'WSM']
🔎 Tickers in report: ['VST', 'NVDA', 'WSM', 'KKR', 'GDDY', 'NRG', 'FICO', 'ERIE', 'LLY', 'STX']
🔎 Prices dict keys: ['ANET', 'CRWD', 'DELL', 'ERIE', 'FICO', 'GDDY', 'KKR', 'LLY', 'NRG', 'NVDA']
✅ Summary HTML block:
 <p><strong>Benchmark (VOO):</strong> $494.78 (+18.2% last 12M)</p><h3>Summary of Changes</h3><p>VST – $70.38 (150.5% last 12M)<br>NVDA – $112.28 (145.8% last 12M)<br>WSM – $150.67 (123.6% last 12M)<br><i>KKR – $116.71 (91.5% last 12M)</i><br><i>GDDY – $143.29 (91.0% last 12M)</i><br>NRG – $73.09 (90.6% last 12M)<br>FICO – $1576.93 (85.0% last 12M)<br><i>ERIE – $387.51 (85.0% last 12M)</i><br>LLY – $821.19 (79.5% last 12M)<br><i>STX – $103.96 (78.5% last 12M)</i><br><s>ANET – $78.53 (— last 12M)<
🧪 DEBUG: Jinja context types and sample values:
  summary_html: <class 'str'> <p><strong>Benchmark (VOO):</strong> $494.78 (+18.2% last 12M)</p><h3>Summary of Changes</h3><p>VST – $70.38 (150.5% last 12M)<br>NVDA – $112.28 (145.8% last 12M)<br>WSM – $150.67 (123.6% last 12M)<br
  formatted_date: <class 'str'> July 26, 2024
  voo_now: <class 'numpy.float64'> 494.78
  voo_return: <class 'numpy.float64'> 0.1821005351681957
  enriched (length): 10
    First stock:
      ticker: <class 'str'> VST
      price: <class 'str'> 70.38
      current_return: <class 'str'> 150.5%
      last_month_return: <class 'str'> 256.2%
      rank_change: <class 'float'> 1.0
✅ Report written: /Users/zacseidel/Documents/GitHub/momentum-screener/reports/momentum_2024-07-26.html
⏳ Generating report for 2024-08-02
Fetching grouped prices for 2024-08-01...
Stored 10578 rows for 2024-08-01
Fetching SPX price for 2024-08-01...
✅ Stored SPX price for 2024-08-01: $499.03
Fetching grouped prices for 2023-08-01...
Stored 10612 rows for 2023-08-01
Fetching SPX price for 2023-08-01...
✅ Stored SPX price for 2023-08-01: $419.38
Fetching grouped prices for 2024-07-01...
Stored 10530 rows for 2024-07-01
Fetching SPX price for 2024-07-01...
✅ Stored SPX price for 2024-07-01: $501.28
Fetching grouped prices for 2023-07-01...
No data for 2023-07-01 — trying previous weekday...
Fetching grouped prices for 2023-06-30...
Stored 10562 rows for 2023-06-30
Fetching SPX price for 2023-07-01...
No SPX data for 2023-07-01 — trying previous weekday...
Fetching SPX price for 2023-06-30...
✅ Stored SPX price for 2023-06-30: $407.28
✅ Stored top 10 picks for 2024-08-02
       current_return last_month_return  current_rank  last_month_rank  \
ticker
VST            172.6%            232.7%           1.0              1.0
NVDA           134.8%            193.8%           2.0              3.0
WSM            109.4%            121.3%           3.0              7.0
DELL           103.2%            163.9%           4.0              5.0
KKR            100.5%             86.6%           5.0             15.0
...               ...               ...           ...              ...
PARA           -30.8%            -36.3%         478.0            486.0
NKE            -32.5%            -30.4%         479.0            480.0
APTV           -33.2%            -33.0%         480.0            484.0
WBD            -34.9%            -43.4%         484.0            489.0
BF.B           -36.8%            -36.9%         487.0            487.0

        rank_change
ticker
VST             0.0
NVDA            1.0
WSM             4.0
DELL            1.0
KKR            10.0
...             ...
PARA            8.0
NKE             1.0
APTV            4.0
WBD             5.0
BF.B            0.0

[259 rows x 5 columns]
🔍 Processing VST (1/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing NVDA (2/10)
  📦 Recent news articles: 5
  ✅ News already fresh — skipping API call.
🔍 Processing WSM (3/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing DELL (4/10)
  📦 Recent news articles: 1
  ✅ News already fresh — skipping API call.
🔍 Processing KKR (5/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing ERIE (6/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing NRG (7/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing HWM (8/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing FICO (9/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing GE (10/10)
  📦 Recent news articles: 0
  🧠 Fetching metadata...
  ⏳ Sleeping for rate limit...
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
📅 Resolved VOO dates: {'current': '2024-08-01', 'one_year_ago': '2023-08-01'}
📈 Retrieved VOO prices: {'2023-08-01': 419.38, '2024-08-01': 499.03}
🔎 All compare tickers: ['GE', 'DELL', 'HWM', 'WSM', 'ERIE', 'NVDA', 'LLY', 'NRG', 'VST', 'KKR', 'FICO', 'GDDY', 'STX']
🔎 Available price tickers: ['DELL', 'ERIE', 'FICO', 'GDDY', 'GE', 'HWM', 'KKR', 'LLY', 'NRG', 'NVDA', 'STX', 'VST', 'WSM']
🔎 Tickers in report: ['VST', 'NVDA', 'WSM', 'DELL', 'KKR', 'ERIE', 'NRG', 'HWM', 'FICO', 'GE']
🔎 Prices dict keys: ['DELL', 'ERIE', 'FICO', 'GDDY', 'GE', 'HWM', 'KKR', 'LLY', 'NRG', 'NVDA']
✅ Summary HTML block:
 <p><strong>Benchmark (VOO):</strong> $499.03 (+19.0% last 12M)</p><h3>Summary of Changes</h3><p>VST – $76.04 (172.6% last 12M)<br>NVDA – $109.21 (134.8% last 12M)<br>WSM – $144.94 (109.4% last 12M)<br><i>DELL – $108.43 (103.2% last 12M)</i><br>KKR – $119.75 (100.5% last 12M)<br>ERIE – $439.72 (99.5% last 12M)<br>NRG – $73.50 (94.3% last 12M)<br><i>HWM – $94.87 (93.7% last 12M)</i><br>FICO – $1578.95 (90.3% last 12M)<br><i>GE – $169.75 (87.9% last 12M)</i><br><s>GDDY – $141.41 (— last 12M)</s><br
🧪 DEBUG: Jinja context types and sample values:
  summary_html: <class 'str'> <p><strong>Benchmark (VOO):</strong> $499.03 (+19.0% last 12M)</p><h3>Summary of Changes</h3><p>VST – $76.04 (172.6% last 12M)<br>NVDA – $109.21 (134.8% last 12M)<br>WSM – $144.94 (109.4% last 12M)<br
  formatted_date: <class 'str'> August 02, 2024
  voo_now: <class 'numpy.float64'> 499.03
  voo_return: <class 'numpy.float64'> 0.18992321999141581
  enriched (length): 10
    First stock:
      ticker: <class 'str'> VST
      price: <class 'str'> 76.04

In [13]:
generate_html_for_date("2025-05-30")

⏳ Generating report for 2025-05-30
Fetching grouped prices for 2025-05-29...
Stored 11089 rows for 2025-05-29
Fetching SPX price for 2025-05-29...
✅ Stored SPX price for 2025-05-29: $542.32
Fetching grouped prices for 2024-05-29...
Stored 10507 rows for 2024-05-29
Fetching SPX price for 2024-05-29...
✅ Stored SPX price for 2024-05-29: $483.69
Fetching grouped prices for 2025-04-29...
Stored 11015 rows for 2025-04-29
Fetching SPX price for 2025-04-29...
✅ Stored SPX price for 2025-04-29: $509.49
Fetching grouped prices for 2024-04-29...
Stored 10459 rows for 2024-04-29
Fetching SPX price for 2024-04-29...
✅ Stored SPX price for 2024-04-29: $468.84
✅ Stored top 10 picks for 2025-05-30
🔍 Processing PLTR (1/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing GEV (2/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing AXON (3/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing TSLA (4/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing TPR (5/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing PODD (6/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing NRG (7/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing DASH (8/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing GILD (9/10)
  📦 Recent news articles: 0
  🧠 Fetching metadata...
  ⏳ Sleeping for rate limit...
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
🔍 Processing AVGO (10/10)
  📦 Recent news articles: 0
  📰 Fetching news...
  ⏳ Sleeping for rate limit...
📅 Resolved VOO dates: {'current': '2025-05-29', 'one_year_ago': '2024-05-29'}
📈 Retrieved VOO prices: {'2024-05-29': 483.69, '2025-05-29': 542.32}
🔎 All compare tickers: ['GILD', 'TPR', 'PODD', 'FTNT', 'AVGO', 'GEV', 'DASH', 'RL', 'TSLA', 'NRG', 'PLTR', 'AXON']
🔎 Available price tickers: ['AVGO', 'AXON', 'DASH', 'FTNT', 'GEV', 'GILD', 'NRG', 'PLTR', 'PODD', 'RL', 'TPR', 'TSLA']
🔎 Tickers in report: ['PLTR', 'GEV', 'AXON', 'TSLA', 'TPR', 'PODD', 'NRG', 'DASH', 'GILD', 'AVGO']
🔎 Prices dict keys: ['AVGO', 'AXON', 'DASH', 'FTNT', 'GEV', 'GILD', 'NRG', 'PLTR', 'PODD', 'RL']
✅ Summary HTML block:
 <p><strong>Benchmark (VOO):</strong> $542.32 (+12.1% last 12M)</p><h3>Summary of Changes</h3><p>PLTR – $122.32 (484.1% last 12M)<br>GEV – $471.17 (165.7% last 12M)<br>AXON – $730.29 (157.0% last 12M)<br>TSLA – $358.43 (103.4% last 12M)<br>TPR – $78.44 (88.9% last 12M)<br>PODD – $323.85 (88.0% last 12M)<br>NRG – $154.47 (84.9% last 12M)<br>DASH – $204.58 (83.1% last 12M)<br><i>GILD – $111.11 (75.0% last 12M)</i><br><i>AVGO – $241.97 (74.0% last 12M)</i><br><s>FTNT – $102.04 (— last 12M)</s><br><s
🧪 DEBUG: Jinja context types and sample values:
  summary_html: <class 'str'> <p><strong>Benchmark (VOO):</strong> $542.32 (+12.1% last 12M)</p><h3>Summary of Changes</h3><p>PLTR – $122.32 (484.1% last 12M)<br>GEV – $471.17 (165.7% last 12M)<br>AXON – $730.29 (157.0% last 12M)<
  formatted_date: <class 'str'> May 30, 2025
  voo_now: <class 'numpy.float64'> 542.32
  voo_return: <class 'numpy.float64'> 0.12121400070292965
  enriched (length): 10
    First stock:
      ticker: <class 'str'> PLTR
      price: <class 'str'> 122.32
      current_return: <class 'str'> 484.1%
      last_month_return: <class 'str'> 408.5%
      rank_change: <class 'float'> 0.0
✅ Report written: /Users/zacseidel/Documents/GitHub/momentum-screener/reports/momentum_2025-05-30.html

In [38]:
!python ../scripts/generate_index.py

✅ Sidebar index written to /Users/zacseidel/Documents/GitHub/momentum-screener/index.html

In [6]:
import sqlite3
from datetime import datetime

In [15]:
DB_PATH = '../data/market_data.sqlite'
DB_PATH

'../data/market_data.sqlite'

In [16]:

with sqlite3.connect(DB_PATH) as conn:
    tables = conn.execute("SELECT name FROM sqlite_master WHERE type='table';").fetchall()

# Show the table names
for table in tables:
    print(table)

('index_allocations',)
('daily_prices',)
('index_constituents',)
('company_metadata',)
('company_news',)
('top10_picks',)

In [21]:
with sqlite3.connect(DB_PATH) as conn:
        voo = pd.read_sql(
            "SELECT * FROM top10_picks",
            conn,
        )
voo

,ticker,current_return,last_month_return,current_rank,last_month_rank,rank_change,date
0,PLTR,425.3%,270.4%,1.0,1.0,0.0,2025-05-02
1,NFLX,105.4%,51.1%,5.0,23.0,18.0,2025-05-02
2,AXON,99.3%,73.8%,6.0,8.0,2.0,2025-05-02
3,VST,78.6%,70.9%,7.0,10.0,3.0,2025-05-02
4,TPR,78.5%,51.5%,8.0,22.0,14.0,2025-05-02
5,PM,77.0%,72.9%,9.0,9.0,0.0,2025-05-02
6,FICO,75.5%,49.0%,10.0,25.0,15.0,2025-05-02
7,WMT,65.5%,48.0%,12.0,28.0,16.0,2025-05-02
8,TTWO,64.8%,40.1%,13.0,42.0,29.0,2025-05-02
9,FTNT,64.0%,42.5%,14.0,37.0,23.0,2025-05-02

In [18]:
voo

date
2023-12-01    421.86
2023-12-08    422.92
2023-12-15    433.09
2023-12-22    435.29
2023-12-29    436.80
               ...
2025-04-24    502.41
2025-05-01    513.35
2025-05-08    519.34
2025-05-15    542.76
2025-05-16    546.26
Name: close, Length: 74, dtype: float64

In [3]:
import sqlite3
import os

# Update this path if needed
BASE_DIR = os.path.abspath("..")  # Assumes you're in the /notebooks directory
DB_PATH = os.path.join(BASE_DIR, "data", "market_data.sqlite")

with sqlite3.connect(DB_PATH) as conn:
    conn.execute("DROP TABLE IF EXISTS top10_picks;")
    print("✅ Dropped 'top10_picks' table.")

✅ Dropped 'top10_picks' table.

In [27]:
import sqlite3
import pandas as pd
import os

# Adjust this if needed
DB_PATH = os.path.join("../data", "market_data.sqlite")

with sqlite3.connect(DB_PATH) as conn:
    voo_dates = pd.read_sql(
        """
        SELECT date, close
        FROM daily_prices
        WHERE ticker = 'PLTR'
        ORDER BY date DESC
        limit 1
        """,
        conn
    )


voo_dates["close"]

0    129.52
Name: close, dtype: float64

In [37]:
import sqlite3
import pandas as pd

DB_PATH = "../data/market_data.sqlite"  # adjust if needed
date_to_check = "2025-05-01"

with sqlite3.connect(DB_PATH) as conn:
    df = pd.read_sql(
        "SELECT ticker, close FROM daily_prices WHERE ticker = 'FICO'",
        conn, params=[date_to_check]
    )

print("🔍 Sample of stored daily_prices for", date_to_check)
print(df.head(25))

# Check types
print("\n🧪 Ticker column types:", df["ticker"].apply(type).unique())
print("🧪 Close column types:", df["close"].apply(type).unique())

# Show all tickers that match the current top 10
top10 = ["PLTR", "NFLX", "AXON", "VST", "TPR", "PM", "FICO", "WMT", "TTWO", "FTNT"]
missing = [t for t in top10 if t not in df["ticker"].str.upper().unique()]
print("\n🚫 Missing tickers from database for that date:", missing)

DatabaseError: Execution failed on sql 'SELECT ticker, close FROM daily_prices WHERE ticker = 'FICO'': Incorrect number of bindings supplied. The current statement uses 0, and there are 1 supplied.

In [5]:
import sqlite3

db_path = "../data/market_data.sqlite"
table_name = "top10_picks"          # e.g. "daily_prices"


with sqlite3.connect(db_path) as conn:
    cur = conn.execute(f"PRAGMA table_info({table_name});")
    schema_rows = cur.fetchall()

# `schema_rows` is a list of tuples:
# (cid, name, type, notnull, dflt_value, pk)
for cid, name, col_type, notnull, default, pk in schema_rows:
    nn = "NOT NULL" if notnull else ""
    pk_flag = "PRIMARY KEY" if pk else ""
    default_str = f"DEFAULT {default}" if default is not None else ""
    print(f"{name:20} {col_type:12} {nn} {default_str} {pk_flag}")

ticker               TEXT
current_return       TEXT
last_month_return    TEXT
current_rank         REAL
last_month_rank      REAL
rank_change          REAL
date                 TEXT
last_week_return     REAL

In [18]:
import sqlite3

In [20]:
db_path = "../data/market_data.sqlite"

def q(sql, params=()):
    """Run a quick SELECT and return a DataFrame."""
    with sqlite3.connect(f'file:{db_path}?mode=ro', uri=True) as conn:
        return pd.read_sql(sql, conn, params=params)

anchor = "2025-06-27"          # ← replace with the date you’re generating
q("""
    SELECT MIN(date), MAX(date)
    FROM daily_prices
    WHERE ticker IN ('AVGO','FFIV','PAYC');
""")

    MIN(date)   MAX(date)
0  2023-06-09  2025-06-26

In [ ]:
# 📈 1-cell smoke test for chart_module ---------------------------------------
# If chart_module.py is in the same folder as the notebook, the import will work.
# Otherwise, add its directory to sys.path.

import os
from chart_module import plot_stock_chart
import matplotlib.pyplot as plt

# ── 1. Set your Polygon API key (skip if it’s already in your shell env) ─────
# ── 2. Generate the figure ───────────────────────────────────────────────────
fig, (ax_candle, ax_vol) = plot_stock_chart(
    ticker="AAPL",         # <— any valid equity ticker
    save_path="exampleplot.png",        # omit to display inline
    index_ticker="VOO"     # comparison ETF
)

plt.show()  # not strictly needed in Jupyter ≥ IPython 5, but explicit is nice

/var/folders/cv/nmfv_60118b7v59r0zjz8y_40000gn/T/ipykernel_59598/3214341513.py:17: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()  # not strictly needed in Jupyter ≥ IPython 5, but explicit is nice